server:
  port: 8066
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharehappy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 2723132855@qq.com
    password: sivzbmjamtlddhbb
    protocol: smtp
    default-encoding: UTF-8

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    ssl: false
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 600000

  level:
    com.simple.example: debug
mybatis:
  mapper-locations: mapper/*Mapper.xml



